apiVersion: batch/v1
kind: Job
metadata:
  name: pi-200000
spec:
  template:
    spec:
      containers:
      - name: pi-200000
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(200000)"]
      restartPolicy: Never
  backoffLimit: 4

