apiVersion: batch/v1
kind: Job
metadata:
  name: pi-10000
spec:
  template:
    spec:
      containers:
      - name: pi-10000
        image: dleehr/perl
      restartPolicy: Never
  backoffLimit: 4

