---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trim-nfs-volume
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trim-copy-nfs
spec:
  template:
    spec:
      containers:
      - name: trim-copy
        image: dleehr/trim-copy:0.1
        command: ["/opt/copy-and-trim.sh"]
        args:
          - "/calrissian/input-data/user-data/dds_Sharma-rawData_rawData_SA05051_S16_L008_R1_001.fastq.gz"
          - "/calrissian/input-data/user-data/dds_Sharma-rawData_rawData_SA05051_S16_L008_R2_001.fastq.gz"
          - "/tmp"
        volumeMounts:
        - mountPath: /calrissian/input-data
          name: calrissian-input-data
        - mountPath: /tmp
          name: tmp
      restartPolicy: Never
      volumes:
      - name: calrissian-input-data
        persistentVolumeClaim:
          claimName: calrissian-input-data
      - name: tmp
        persistentVolumeClaim:
          claimName: trim-nfs-volume
  backOffLimit: 0
